### ISSUE TITLE
Fog of War

### ISSUE THREAD

**Issue by Cheeseless** [Cheeseless/comp313-001-team01-project#1]
Fog of War - units have a vision range, outside of which the level map is darkened, and units and effects that do not belong to the active player are not visible.

The main alternative is a fully visible play field, more similar to traditional board games like Chess, or classic tactics video games like Final Fantasy Tactics.

**Comment by smonroy** [comment]
If the game is going to be for this academic project only for two humans players sharing the same screen, it doesn't have any sense to try to implement the Fog of War.

**Comment by smonroy** [comment]
I guess that it is better to use the fully visible play field.

**Comment by Cheeseless** [comment]
I agree. We'll declare it formally in the Wiki.
