### ISSUE TITLE
Unit combative interaction

### ISSUE THREAD

**Issue by RD5000** [Cheeseless/comp313-001-team01-project#12]
Units can damage one other unit of an opposing team.
Just straight damage is fine, 
De-buffing or non-damaging combative abilities can be added later.

Dependent on [Unit Generation](https://github.com/Cheeseless/comp313-001-team01-project/issues/8)
and [Test Level Development](https://github.com/Cheeseless/comp313-001-team01-project/issues/9)

**Comment by Cheeseless** [comment]
Needs to be replaced by issues related to ability implementation
