### ISSUE TITLE
Unit movement

### ISSUE THREAD

**Issue by RD5000** [Cheeseless/comp313-001-team01-project#14]
Basic non-calculative movement.
If the thing can go from a to b that's good enough.
Terrain calculation can be added later.
Dependent on [Unit Generation](https://github.com/Cheeseless/comp313-001-team01-project/issues/8)
and [Test Level Development](https://github.com/Cheeseless/comp313-001-team01-project/issues/9)
and #17

**Comment by deskpal** [comment]
@RD5000 - Please make sure that each issue is assigned to one and only one person. Also, please assign the issue to a Milestone and use labels (for instance "user story", "task", "bug"...)

**Comment by Cheeseless** [comment]
Basic movement takes terrain into account
