### ISSUE TITLE
Game Cell Properties

### ISSUE THREAD

**Issue by RD5000** [Cheeseless/comp313-001-team01-project#21]
Cost of movement
Modifier properties

**Comment by Cheeseless** [comment]
Slow terrain: -1 speed
Fast terrain: +1 speed
both of these are functionally equivalent to raising the cost of movement  through the tile by one, so they should probably be properties of the tile type.

Damaging terrain: unit on this tile loses 1 hp at start of turn, end of turn, and when moving into this tile.

**Comment by Cheeseless** [comment]
Cover terrain: unit has +1 defense while in this tile.

**Comment by wes-angus** [comment]
Closed #21
